Repository streetcomplete/StreetComplete, pull requests merged in 2022-01, with the labels that each got.

#3633 Allow converting ways into steps in smoothness quest
  app/src/main/java/de/westnordost/streetcomplete/quests/smoothness/AddPathSmoothness.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/smoothness/AddRoadSmoothness.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/smoothness/AddSmoothnessForm.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/smoothness/SmoothnessAnswer.kt
Labels: enhancement

#3630 Add smoothness emojis as icons
  app/src/main/java/de/westnordost/streetcomplete/ktx/Drawable.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/smoothness/AddSmoothnessForm.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/smoothness/SmoothnessItem.kt
  app/src/main/res/drawable/ic_smoothness_car.xml
  app/src/main/res/drawable/ic_smoothness_city_bike.xml
  app/src/main/res/drawable/ic_smoothness_pedestrian.xml
  app/src/main/res/drawable/ic_smoothness_pickup_truck.xml
  app/src/main/res/drawable/ic_smoothness_scooter.xml
  app/src/main/res/drawable/ic_smoothness_skateboard.xml
  app/src/main/res/drawable/ic_smoothness_suv.xml
  app/src/main/res/drawable/ic_smoothness_tractor.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  res/graphics/authors.txt
  res/graphics/smoothness icons/car.svg
  res/graphics/smoothness icons/city_bike.svg
  res/graphics/smoothness icons/pedestrian.svg
  res/graphics/smoothness icons/pickup_truck.svg
  res/graphics/smoothness icons/scooter.svg
  res/graphics/smoothness icons/skateboard.svg
  res/graphics/smoothness icons/suv.svg
  res/graphics/smoothness icons/tractor.svg
Labels: usability

#3631 replace LocationRequestFragment with suspending api
  app/src/main/java/de/westnordost/streetcomplete/ApplicationModule.kt
  app/src/main/java/de/westnordost/streetcomplete/MainActivity.kt
  app/src/main/java/de/westnordost/streetcomplete/Prefs.kt
  app/src/main/java/de/westnordost/streetcomplete/data/quest/QuestAutoSyncer.kt
  app/src/main/java/de/westnordost/streetcomplete/ktx/Context.kt
  app/src/main/java/de/westnordost/streetcomplete/ktx/Double.kt
  app/src/main/java/de/westnordost/streetcomplete/ktx/Location.kt
  app/src/main/java/de/westnordost/streetcomplete/location/LocationRequestFragment.kt
  app/src/main/java/de/westnordost/streetcomplete/location/LocationRequester.kt
  app/src/main/java/de/westnordost/streetcomplete/location/LocationUtil.kt
  app/src/main/java/de/westnordost/streetcomplete/map/LocationAwareMapFragment.kt
  app/src/main/java/de/westnordost/streetcomplete/map/MainFragment.kt
  app/src/main/java/de/westnordost/streetcomplete/map/components/CurrentLocationMapComponent.kt
  app/src/main/java/de/westnordost/streetcomplete/util/ActivityForResultLauncher.kt
Labels: code cleanup
