Repository streetcomplete/StreetComplete, pull requests merged in 2023-11, with the labels that each got.

#5377 Replace deprecated toLowerCase / toUpperCase with lowercase / uppercase
  buildSrc/src/main/java/POEditorDownloader.kt
  buildSrc/src/main/java/UpdateNsiPresetsTask.kt
  buildSrc/src/main/java/UpdateStoreDescriptionsTask.kt
  buildSrc/src/main/java/UpdateWebsiteTranslationsTask.kt
Labels: code cleanup

#5332 Extend General fee with Sanitary Dump Stations
  app/src/main/java/de/westnordost/streetcomplete/quests/general_fee/AddGeneralFee.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#5363 New Quest: Does this caravan area have a sanitary_dump_station?
  app/src/main/java/de/westnordost/streetcomplete/quests/QuestsModule.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/sanitary_dump_station/AddSanitaryDumpStation.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/sanitary_dump_station/AddSanitaryDumpStationForm.kt
  app/src/main/res/drawable/ic_quest_caravan.xml
  app/src/main/res/drawable/sanitary_dump_station_sign1.xml
  app/src/main/res/drawable/sanitary_dump_station_sign2.xml
  app/src/main/res/layout/quest_sanitary_dump_station.xml
  app/src/main/res/values/strings.xml
  res/graphics/authors.txt
Labels: new quest

#5371 Grill fuel quest -- add OtherAnswer that this is just a firering, not a Grill
  app/src/main/java/de/westnordost/streetcomplete/quests/bbq_fuel/AddBbqFuel.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/bbq_fuel/AddBbqFuelForm.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/bbq_fuel/BbqFuel.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/bbq_fuel/BbqFuelAnswer.kt
  app/src/main/res/values/strings.xml
Labels: enhancement
