Repository streetcomplete/StreetComplete, pull requests merged in 2024-01, with the labels that each got.

#5430 Simplify max speed quest logic
  app/src/main/java/de/westnordost/streetcomplete/quests/max_speed/AddMaxSpeedForm.kt
Labels: code cleanup

#5431 Update Ktlint to v1.1.0
  .editorconfig
  .github/workflows/lint.yml
  CONTRIBUTING.md
  app/src/main/java/de/westnordost/streetcomplete/Prefs.kt
  app/src/main/java/de/westnordost/streetcomplete/osm/surface/SurfaceUtils.kt
  app/src/main/java/de/westnordost/streetcomplete/screens/measure/MeasureContract.kt
  app/src/main/java/de/westnordost/streetcomplete/screens/user/profile/ProfileFragment.kt
  app/src/main/java/de/westnordost/streetcomplete/view/image_select/GroupedImageSelectAdapter.kt
Labels: code cleanup

#5442 Multiplatform JSON parsing (kotlinx.serialization)
  app/src/androidTest/java/de/westnordost/streetcomplete/quests/oneway_suspects/TrafficFlowSegmentsApiTest.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/StreetCompleteImageUploader.kt
  app/src/main/java/de/westnordost/streetcomplete/data/user/statistics/StatisticsParser.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/oneway_suspects/data/TrafficFlowSegment.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/oneway_suspects/data/TrafficFlowSegmentsApi.kt
  app/src/test/java/de/westnordost/streetcomplete/data/user/statistics/StatisticsParserTest.kt
Labels: code cleanup

#5359 Disable restoring hidden quests when there are none to unhide.
  app/src/androidTest/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmQuestsHiddenDaoTest.kt
  app/src/androidTest/java/de/westnordost/streetcomplete/data/osmnotes/notequests/NoteQuestsHiddenDaoTest.kt
  app/src/main/java/de/westnordost/streetcomplete/data/edithistory/EditHistoryController.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmQuestController.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmQuestModule.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmQuestsHiddenController.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmQuestsHiddenDao.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmQuestsHiddenSource.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/notequests/NoteQuestsHiddenDao.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/notequests/OsmNoteQuestController.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/notequests/OsmNoteQuestModule.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/notequests/OsmNoteQuestsHiddenController.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osmnotes/notequests/OsmNoteQuestsHiddenSource.kt
  app/src/main/java/de/westnordost/streetcomplete/quests/AbstractOsmQuestForm.kt
  app/src/main/java/de/westnordost/streetcomplete/screens/settings/SettingsFragment.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/de/westnordost/streetcomplete/data/edithistory/EditHistoryControllerTest.kt
  app/src/test/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmQuestControllerTest.kt
  app/src/test/java/de/westnordost/streetcomplete/data/osmnotes/notequests/OsmNoteQuestControllerTest.kt
  res/documentation/overview_data_flow.drawio
  res/documentation/overview_data_flow.svg
Labels: usability

#5439 Move changelog from YAML to Markdown
  CHANGELOG.md
  app/build.gradle.kts
  app/src/main/java/de/westnordost/streetcomplete/screens/about/ChangelogFragment.kt
  app/src/main/java/de/westnordost/streetcomplete/util/ktx/Resources.kt
  app/src/main/java/de/westnordost/streetcomplete/util/ktx/String.kt
  app/src/main/res/layout/dialog_whats_new.xml
  app/src/main/res/layout/fragment_changelog.xml
  app/src/main/res/layout/row_changelog.xml
  app/src/main/res/raw/changelog.html
  app/src/main/res/raw/changelog.yml
  app/src/test/java/de/westnordost/streetcomplete/util/ktx/StringTest.kt
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/UpdateChangelogTask.kt
  res/documentation/creating new release.md
Labels: code cleanup

#5307 Migrate PolylinesSerializer to kotlinx-io
  app/build.gradle.kts
  app/src/main/java/de/westnordost/streetcomplete/data/DatabaseInitializer.kt
  app/src/main/java/de/westnordost/streetcomplete/data/osm/geometry/PolylinesSerializer.kt
Labels: code cleanup, hacktoberfest-accepted
